-- Clutch DB 스키마 — ERD Cloud import 용
-- 생성: 2026-08-12 · 마이그레이션 V1~V5 적용 상태의 실제 MySQL 8.4 에서 추출
--
-- FK 의존성 순서로 재배열했다 (알파벳순이면 참조 대상이 뒤에 와서 import 가 깨진다).
-- flyway_schema_history 는 Flyway 관리 테이블이라 제외했다.

CREATE TABLE `user` (
  `user_id` bigint NOT NULL AUTO_INCREMENT COMMENT '식별자',
  `role` varchar(20) NOT NULL COMMENT '권한(ADMIN, USER)',
  `email` varchar(255) NOT NULL COMMENT '이메일',
  `point` bigint NOT NULL DEFAULT '0' COMMENT '포인트',
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성시각',
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정시각',
  PRIMARY KEY (`user_id`),
  UNIQUE KEY `uk_user_email` (`email`),
  CONSTRAINT `chk_user_point` CHECK ((`point` >= 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `coupon_type` (
  `coupon_type_id` bigint NOT NULL AUTO_INCREMENT COMMENT '식별자',
  `coupon_name` varchar(100) NOT NULL COMMENT '쿠폰이름',
  `discount_type` varchar(20) NOT NULL DEFAULT 'RATE' COMMENT '할인타입(RATE 또는 AMOUNT)',
  `discount_value` decimal(10,2) NOT NULL COMMENT '할인값',
  `status` varchar(30) NOT NULL COMMENT '쿠폰상태',
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성시각',
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정시각',
  PRIMARY KEY (`coupon_type_id`),
  CONSTRAINT `chk_coupon_type_discount_type` CHECK ((`discount_type` in (_utf8mb4'RATE',_utf8mb4'AMOUNT'))),
  CONSTRAINT `chk_coupon_type_discount_value` CHECK ((((`discount_type` = _utf8mb4'RATE') and (`discount_value` between 0 and 100)) or ((`discount_type` = _utf8mb4'AMOUNT') and (`discount_value` > 0))))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `esports_match` (
  `esports_match_id` bigint NOT NULL AUTO_INCREMENT COMMENT '내부 매치 식별자',
  `external_match_id` varchar(32) NOT NULL COMMENT 'LoL Esports matchId',
  `league_external_id` varchar(32) NOT NULL COMMENT '수집 대상 리그 외부 식별자',
  `season_key` varchar(50) NOT NULL COMMENT 'H2H 집계 시즌 키(예: 2026)',
  `tournament_external_id` varchar(32) DEFAULT NULL COMMENT '확인된 경우 대회 외부 식별자',
  `block_name` varchar(100) DEFAULT NULL COMMENT '주차/라운드 표시명',
  `scheduled_at` datetime(6) NOT NULL COMMENT '예정 시작 시각(UTC)',
  `started_at` datetime(6) DEFAULT NULL COMMENT '실제 매치 시작 시각(UTC)',
  `lifecycle_status` varchar(20) NOT NULL COMMENT 'unstarted/inProgress/completed 원본 상태',
  `best_of` int DEFAULT NULL COMMENT '다전제 수(1/3/5 등)',
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 시각',
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 시각',
  PRIMARY KEY (`esports_match_id`),
  UNIQUE KEY `uk_esports_match_external_id` (`external_match_id`),
  KEY `idx_esports_match_season_schedule` (`league_external_id`,`season_key`,`scheduled_at`),
  KEY `idx_esports_match_tournament_schedule` (`tournament_external_id`,`scheduled_at`),
  KEY `idx_esports_match_status_schedule` (`lifecycle_status`,`scheduled_at`),
  CONSTRAINT `chk_esports_match_best_of` CHECK (((`best_of` is null) or (`best_of` > 0))),
  CONSTRAINT `chk_esports_match_season_key` CHECK ((char_length(trim(`season_key`)) > 0))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `match_team` (
  `match_team_id` bigint NOT NULL AUTO_INCREMENT COMMENT '매치 참가 팀 식별자',
  `match_id` bigint NOT NULL COMMENT '내부 매치 식별자',
  `external_team_id` varchar(32) DEFAULT NULL COMMENT 'LoL Esports 팀 식별자; TBD이면 NULL',
  `display_order` int NOT NULL COMMENT '매치 헤더 표시 순서(1/2)',
  `team_code` varchar(16) DEFAULT NULL COMMENT '경기 당시 팀 코드',
  `team_name` varchar(100) DEFAULT NULL COMMENT '경기 당시 팀 이름',
  `team_image_url` varchar(2048) DEFAULT NULL COMMENT '경기 당시 팀 로고 URL',
  `outcome` varchar(10) DEFAULT NULL COMMENT '매치 기준 win/loss',
  `game_wins` int DEFAULT NULL COMMENT '해당 매치 세트 승수',
  `record_wins_snapshot` int DEFAULT NULL COMMENT '일정 응답 당시 전적 승수',
  `record_losses_snapshot` int DEFAULT NULL COMMENT '일정 응답 당시 전적 패수',
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 시각',
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 시각',
  PRIMARY KEY (`match_team_id`),
  UNIQUE KEY `uk_match_team_match_order` (`match_id`,`display_order`),
  UNIQUE KEY `uk_match_team_id_match` (`match_team_id`,`match_id`),
  UNIQUE KEY `uk_match_team_match_external` (`match_id`,`external_team_id`),
  KEY `idx_match_team_external_match` (`external_team_id`,`match_id`),
  KEY `idx_match_team_match_outcome` (`match_id`,`outcome`),
  CONSTRAINT `fk_match_team_match` FOREIGN KEY (`match_id`) REFERENCES `esports_match` (`esports_match_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `chk_match_team_display_order` CHECK ((`display_order` in (1,2))),
  CONSTRAINT `chk_match_team_game_wins` CHECK (((`game_wins` is null) or (`game_wins` >= 0))),
  CONSTRAINT `chk_match_team_outcome` CHECK (((`outcome` is null) or (`outcome` in (_utf8mb4'win',_utf8mb4'loss')))),
  CONSTRAINT `chk_match_team_record_losses` CHECK (((`record_losses_snapshot` is null) or (`record_losses_snapshot` >= 0))),
  CONSTRAINT `chk_match_team_record_wins` CHECK (((`record_wins_snapshot` is null) or (`record_wins_snapshot` >= 0)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `esports_game` (
  `esports_game_id` bigint NOT NULL AUTO_INCREMENT COMMENT '내부 세트 식별자',
  `external_game_id` varchar(32) NOT NULL COMMENT 'LoL Esports gameId',
  `match_id` bigint NOT NULL COMMENT '내부 매치 식별자',
  `game_number` int NOT NULL COMMENT '매치 내 세트 번호',
  `blue_match_team_id` bigint DEFAULT NULL COMMENT '이 세트의 블루 진영 match_team 식별자',
  `red_match_team_id` bigint DEFAULT NULL COMMENT '이 세트의 레드 진영 match_team 식별자',
  `lifecycle_status` varchar(20) NOT NULL COMMENT 'unstarted/inProgress/completed 원본 상태',
  `telemetry_state` varchar(30) DEFAULT NULL COMMENT '마지막 Window frame gameState 원본',
  `patch_version` varchar(50) DEFAULT NULL COMMENT '피드 patch/build 버전',
  `started_at` datetime(6) DEFAULT NULL COMMENT '게임 시작 시각 및 경과 시간 계산 기준(UTC)',
  `ended_at` datetime(6) DEFAULT NULL COMMENT '게임 종료 시각(UTC)',
  `duration_seconds` int DEFAULT NULL COMMENT '최종 게임 경과 초',
  `final_window_frame_at` datetime(6) DEFAULT NULL COMMENT '최종 Window 통계 frame 시각(UTC)',
  `final_details_frame_at` datetime(6) DEFAULT NULL COMMENT '최종 Details 통계 frame 시각(UTC)',
  `blue_total_gold` bigint DEFAULT NULL COMMENT '블루 최종 총 골드',
  `red_total_gold` bigint DEFAULT NULL COMMENT '레드 최종 총 골드',
  `blue_total_kills` int DEFAULT NULL COMMENT '블루 최종 킬',
  `red_total_kills` int DEFAULT NULL COMMENT '레드 최종 킬',
  `blue_towers` int DEFAULT NULL COMMENT '블루 최종 포탑 수',
  `red_towers` int DEFAULT NULL COMMENT '레드 최종 포탑 수',
  `blue_inhibitors` int DEFAULT NULL COMMENT '블루 최종 억제기 수',
  `red_inhibitors` int DEFAULT NULL COMMENT '레드 최종 억제기 수',
  `blue_barons` int DEFAULT NULL COMMENT '블루 최종 바론 수',
  `red_barons` int DEFAULT NULL COMMENT '레드 최종 바론 수',
  `objectives_json` json DEFAULT NULL COMMENT '그래프용 오브젝트 이벤트 배열',
  `window_collection_status` varchar(20) NOT NULL DEFAULT 'PENDING' COMMENT 'Window 수집 상태',
  `details_collection_status` varchar(20) NOT NULL DEFAULT 'PENDING' COMMENT 'Details 수집 상태',
  `timeline_collection_status` varchar(20) NOT NULL DEFAULT 'PENDING' COMMENT 'Timeline 수집 상태',
  `timeline_covered_from_seconds` int DEFAULT NULL COMMENT '수집된 timeline 시작 경과 초',
  `timeline_covered_to_seconds` int DEFAULT NULL COMMENT '수집된 timeline 종료 경과 초',
  `finalized_at` datetime(6) DEFAULT NULL COMMENT '필수 데이터 최종 확정 시각',
  `last_collection_error` varchar(1000) DEFAULT NULL COMMENT '마지막 수집 오류 요약',
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 시각',
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 시각',
  PRIMARY KEY (`esports_game_id`),
  UNIQUE KEY `uk_esports_game_external_id` (`external_game_id`),
  UNIQUE KEY `uk_esports_game_match_number` (`match_id`,`game_number`),
  KEY `idx_esports_game_match_status` (`match_id`,`lifecycle_status`),
  KEY `idx_esports_game_blue_match_team` (`blue_match_team_id`,`match_id`),
  KEY `idx_esports_game_red_match_team` (`red_match_team_id`,`match_id`),
  CONSTRAINT `fk_esports_game_blue_match_team` FOREIGN KEY (`blue_match_team_id`, `match_id`) REFERENCES `match_team` (`match_team_id`, `match_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_esports_game_match` FOREIGN KEY (`match_id`) REFERENCES `esports_match` (`esports_match_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_esports_game_red_match_team` FOREIGN KEY (`red_match_team_id`, `match_id`) REFERENCES `match_team` (`match_team_id`, `match_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `chk_esports_game_details_status` CHECK ((`details_collection_status` in (_utf8mb4'PENDING',_utf8mb4'PARTIAL',_utf8mb4'COMPLETE',_utf8mb4'UNAVAILABLE'))),
  CONSTRAINT `chk_esports_game_different_sides` CHECK (((`blue_match_team_id` is null) or (`red_match_team_id` is null) or (`blue_match_team_id` <> `red_match_team_id`))),
  CONSTRAINT `chk_esports_game_duration` CHECK (((`duration_seconds` is null) or (`duration_seconds` >= 0))),
  CONSTRAINT `chk_esports_game_number` CHECK ((`game_number` > 0)),
  CONSTRAINT `chk_esports_game_objectives_json` CHECK (((`objectives_json` is null) or (json_type(`objectives_json`) = _utf8mb4'ARRAY'))),
  CONSTRAINT `chk_esports_game_period` CHECK (((`ended_at` is null) or (`started_at` is null) or (`ended_at` >= `started_at`))),
  CONSTRAINT `chk_esports_game_team_stats` CHECK ((((`blue_total_gold` is null) or (`blue_total_gold` >= 0)) and ((`red_total_gold` is null) or (`red_total_gold` >= 0)) and ((`blue_total_kills` is null) or (`blue_total_kills` >= 0)) and ((`red_total_kills` is null) or (`red_total_kills` >= 0)) and ((`blue_towers` is null) or (`blue_towers` >= 0)) and ((`red_towers` is null) or (`red_towers` >= 0)) and ((`blue_inhibitors` is null) or (`blue_inhibitors` >= 0)) and ((`red_inhibitors` is null) or (`red_inhibitors` >= 0)) and ((`blue_barons` is null) or (`blue_barons` >= 0)) and ((`red_barons` is null) or (`red_barons` >= 0)))),
  CONSTRAINT `chk_esports_game_timeline_coverage` CHECK ((((`timeline_covered_from_seconds` is null) or (`timeline_covered_from_seconds` >= 0)) and ((`timeline_covered_to_seconds` is null) or (`timeline_covered_to_seconds` >= 0)) and ((`timeline_covered_from_seconds` is null) or (`timeline_covered_to_seconds` is null) or (`timeline_covered_to_seconds` >= `timeline_covered_from_seconds`)))),
  CONSTRAINT `chk_esports_game_timeline_status` CHECK ((`timeline_collection_status` in (_utf8mb4'PENDING',_utf8mb4'PARTIAL',_utf8mb4'COMPLETE',_utf8mb4'UNAVAILABLE'))),
  CONSTRAINT `chk_esports_game_window_status` CHECK ((`window_collection_status` in (_utf8mb4'PENDING',_utf8mb4'PARTIAL',_utf8mb4'COMPLETE',_utf8mb4'UNAVAILABLE')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `game_player_stat` (
  `game_player_stat_id` bigint NOT NULL AUTO_INCREMENT COMMENT '세트별 선수 기록 식별자',
  `game_id` bigint NOT NULL COMMENT '내부 세트 식별자',
  `match_team_id` bigint DEFAULT NULL COMMENT '선수가 속한 match_team 식별자',
  `participant_no` int NOT NULL COMMENT '세트 내부 참가 번호(1~10)',
  `side` varchar(4) NOT NULL COMMENT 'blue/red',
  `external_player_id` varchar(32) DEFAULT NULL COMMENT 'upstream esportsPlayerId',
  `summoner_name` varchar(100) DEFAULT NULL COMMENT '경기 당시 소환사명',
  `champion_id` varchar(50) DEFAULT NULL COMMENT '챔피언 식별자',
  `role` varchar(20) DEFAULT NULL COMMENT 'top/jungle/mid/bottom/support',
  `level` int DEFAULT NULL COMMENT '최종 레벨',
  `kills` int DEFAULT NULL COMMENT '최종 킬',
  `deaths` int DEFAULT NULL COMMENT '최종 데스',
  `assists` int DEFAULT NULL COMMENT '최종 어시스트',
  `creep_score` int DEFAULT NULL COMMENT '최종 CS',
  `total_gold` bigint DEFAULT NULL COMMENT 'Window scoreboard 총 골드',
  `total_gold_earned` bigint DEFAULT NULL COMMENT 'Details 획득 골드',
  `kill_participation_ratio` decimal(7,6) DEFAULT NULL COMMENT '킬 관여율 원본 비율(0~1)',
  `champion_damage_share_ratio` decimal(7,6) DEFAULT NULL COMMENT '챔피언 피해 비중 원본 비율(0~1)',
  `wards_placed` int DEFAULT NULL COMMENT '설치 와드 수',
  `wards_destroyed` int DEFAULT NULL COMMENT '파괴 와드 수',
  `items_json` json DEFAULT NULL COMMENT '최종 아이템 ID 순서 배열',
  `perks_json` json DEFAULT NULL COMMENT 'style/subStyle/perks 객체',
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성 시각',
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정 시각',
  PRIMARY KEY (`game_player_stat_id`),
  UNIQUE KEY `uk_game_player_stat_game_participant` (`game_id`,`participant_no`),
  KEY `idx_game_player_stat_game_side` (`game_id`,`side`),
  KEY `idx_game_player_stat_match_team` (`match_team_id`),
  KEY `idx_game_player_stat_external_player` (`external_player_id`,`game_id`),
  CONSTRAINT `fk_game_player_stat_game` FOREIGN KEY (`game_id`) REFERENCES `esports_game` (`esports_game_id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `fk_game_player_stat_match_team` FOREIGN KEY (`match_team_id`) REFERENCES `match_team` (`match_team_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `chk_game_player_stat_counters` CHECK ((((`level` is null) or (`level` >= 0)) and ((`kills` is null) or (`kills` >= 0)) and ((`deaths` is null) or (`deaths` >= 0)) and ((`assists` is null) or (`assists` >= 0)) and ((`creep_score` is null) or (`creep_score` >= 0)) and ((`total_gold` is null) or (`total_gold` >= 0)) and ((`total_gold_earned` is null) or (`total_gold_earned` >= 0)) and ((`wards_placed` is null) or (`wards_placed` >= 0)) and ((`wards_destroyed` is null) or (`wards_destroyed` >= 0)))),
  CONSTRAINT `chk_game_player_stat_items_json` CHECK (((`items_json` is null) or (json_type(`items_json`) = _utf8mb4'ARRAY'))),
  CONSTRAINT `chk_game_player_stat_participant` CHECK ((`participant_no` between 1 and 10)),
  CONSTRAINT `chk_game_player_stat_perks_json` CHECK (((`perks_json` is null) or (json_type(`perks_json`) = _utf8mb4'OBJECT'))),
  CONSTRAINT `chk_game_player_stat_ratios` CHECK ((((`kill_participation_ratio` is null) or (`kill_participation_ratio` between 0 and 1)) and ((`champion_damage_share_ratio` is null) or (`champion_damage_share_ratio` between 0 and 1)))),
  CONSTRAINT `chk_game_player_stat_side` CHECK ((`side` in (_utf8mb4'blue',_utf8mb4'red')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `game_timeline_point` (
  `game_timeline_point_id` bigint NOT NULL AUTO_INCREMENT COMMENT '게임 시계열 지점 식별자',
  `game_id` bigint NOT NULL COMMENT '내부 세트 식별자',
  `game_time_seconds` int NOT NULL COMMENT '게임 시작 기준 경과 초',
  `blue_gold` bigint NOT NULL COMMENT '블루 총 골드',
  `red_gold` bigint NOT NULL COMMENT '레드 총 골드',
  `blue_kills` int NOT NULL COMMENT '블루 총 킬',
  `red_kills` int NOT NULL COMMENT '레드 총 킬',
  PRIMARY KEY (`game_timeline_point_id`),
  UNIQUE KEY `uk_timeline_game_time` (`game_id`,`game_time_seconds`),
  CONSTRAINT `fk_game_timeline_point_game` FOREIGN KEY (`game_id`) REFERENCES `esports_game` (`esports_game_id`) ON DELETE CASCADE ON UPDATE RESTRICT,
  CONSTRAINT `chk_game_timeline_point_nonnegative` CHECK (((`game_time_seconds` >= 0) and (`blue_gold` >= 0) and (`red_gold` >= 0) and (`blue_kills` >= 0) and (`red_kills` >= 0)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `match_view_session` (
  `match_view_session_id` bigint NOT NULL AUTO_INCREMENT COMMENT '식별자',
  `user_id` bigint NOT NULL COMMENT '유저식별자',
  `esports_match_id` bigint NOT NULL COMMENT 'esports_match 식별자',
  `started_at` datetime(6) NOT NULL COMMENT '시청시작시각',
  `ended_at` datetime(6) DEFAULT NULL COMMENT '시청종료시각',
  `session_status` varchar(30) NOT NULL COMMENT '세션상태',
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성시각',
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정시각',
  PRIMARY KEY (`match_view_session_id`),
  KEY `idx_match_view_session_user` (`user_id`),
  KEY `idx_match_view_session_esports_match_status` (`esports_match_id`,`session_status`),
  CONSTRAINT `fk_match_view_session_esports_match` FOREIGN KEY (`esports_match_id`) REFERENCES `esports_match` (`esports_match_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `chk_match_view_session_period` CHECK (((`ended_at` is null) or (`ended_at` >= `started_at`)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `esports_match_event` (
  `match_event_id` bigint NOT NULL AUTO_INCREMENT COMMENT '식별자',
  `esports_match_id` bigint NOT NULL COMMENT '경기식별자',
  `external_event_id` varchar(100) DEFAULT NULL COMMENT '외부이벤트식별자(중복 감지 방지용)',
  `event_type` varchar(50) NOT NULL COMMENT '이벤트유형(FIRST_BLOOD/BARON/PENTAKILL 등)',
  `occurred_at` datetime(6) NOT NULL COMMENT '발생시각',
  `event_data` json DEFAULT NULL COMMENT '이벤트상세데이터',
  `processed_at` datetime(6) DEFAULT NULL COMMENT '쿠폰 발동 처리 시각(미처리면 NULL)',
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성시각',
  PRIMARY KEY (`match_event_id`),
  UNIQUE KEY `uk_match_event_external` (`external_event_id`),
  KEY `idx_match_event_match_type` (`esports_match_id`,`event_type`),
  KEY `idx_match_event_unprocessed` (`processed_at`,`occurred_at`),
  CONSTRAINT `fk_match_event_esports_match` FOREIGN KEY (`esports_match_id`) REFERENCES `esports_match` (`esports_match_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `chk_match_event_data_json` CHECK (((`event_data` is null) or (json_type(`event_data`) = _utf8mb4'OBJECT')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `coupon_event` (
  `coupon_event_id` bigint NOT NULL AUTO_INCREMENT COMMENT '식별자',
  `esports_match_id` bigint NOT NULL COMMENT 'esports_match 식별자',
  `event_name` varchar(200) NOT NULL DEFAULT '' COMMENT '이벤트이름',
  `trigger_type` varchar(50) NOT NULL DEFAULT 'MANUAL' COMMENT '이벤트발생조건',
  `event_status` varchar(20) NOT NULL DEFAULT 'READY' COMMENT '전체이벤트상태',
  `claim_window_seconds` int NOT NULL DEFAULT '300' COMMENT '오픈 후 신청 가능 시간(초)',
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성시각',
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정시각',
  PRIMARY KEY (`coupon_event_id`),
  UNIQUE KEY `uk_coupon_event_match_trigger` (`esports_match_id`,`trigger_type`),
  KEY `idx_coupon_event_esports_match_id` (`esports_match_id`),
  CONSTRAINT `fk_coupon_event_esports_match` FOREIGN KEY (`esports_match_id`) REFERENCES `esports_match` (`esports_match_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `chk_coupon_event_claim_window` CHECK ((`claim_window_seconds` > 0)),
  CONSTRAINT `chk_coupon_event_status` CHECK ((`event_status` in (_utf8mb4'READY',_utf8mb4'OPEN',_utf8mb4'CLOSED',_utf8mb4'CANCELLED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `coupon_event_occurrence` (
  `coupon_event_occurrence_id` bigint NOT NULL AUTO_INCREMENT COMMENT '식별자',
  `coupon_event_id` bigint NOT NULL COMMENT '쿠폰이벤트식별자',
  `match_event_id` bigint DEFAULT NULL COMMENT '발동 근거가 된 경기 이벤트',
  `source_event_key` varchar(100) DEFAULT NULL COMMENT '외부 이벤트 중복 발동 방지 키',
  `game_time_seconds` int DEFAULT NULL COMMENT '게임 시작 후 발생 초',
  `source_occurred_at` datetime(6) DEFAULT NULL COMMENT '원본 데이터상 실제 발생 시각',
  `detected_at` datetime(6) NOT NULL COMMENT '서버가 감지한 시각',
  `opened_at` datetime(6) NOT NULL COMMENT '신청 오픈 시각',
  `expires_at` datetime(6) NOT NULL COMMENT '신청 마감 시각',
  `closed_at` datetime(6) DEFAULT NULL COMMENT '실제 종료 시각',
  `occurrence_status` varchar(20) NOT NULL DEFAULT 'OPEN' COMMENT '회차상태',
  `close_reason` varchar(50) DEFAULT NULL COMMENT '종료사유(SOLD_OUT/EXPIRED/CANCELLED)',
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성시각',
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정시각',
  PRIMARY KEY (`coupon_event_occurrence_id`),
  UNIQUE KEY `uk_occurrence_source_key` (`source_event_key`),
  KEY `idx_occurrence_event_status` (`coupon_event_id`,`occurrence_status`),
  KEY `idx_occurrence_open_window` (`occurrence_status`,`expires_at`),
  KEY `idx_occurrence_match_event` (`match_event_id`),
  CONSTRAINT `fk_occurrence_coupon_event` FOREIGN KEY (`coupon_event_id`) REFERENCES `coupon_event` (`coupon_event_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `fk_occurrence_match_event` FOREIGN KEY (`match_event_id`) REFERENCES `esports_match_event` (`match_event_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `chk_occurrence_game_time` CHECK (((`game_time_seconds` is null) or (`game_time_seconds` >= 0))),
  CONSTRAINT `chk_occurrence_period` CHECK ((`expires_at` > `opened_at`)),
  CONSTRAINT `chk_occurrence_status` CHECK ((`occurrence_status` in (_utf8mb4'OPEN',_utf8mb4'CLOSED',_utf8mb4'CANCELLED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `coupon_event_item` (
  `coupon_event_item_id` bigint NOT NULL AUTO_INCREMENT COMMENT '식별자',
  `coupon_event_id` bigint NOT NULL COMMENT '쿠폰이벤트식별자',
  `coupon_type_id` bigint NOT NULL COMMENT '쿠폰타입식별자',
  `quantity` int NOT NULL COMMENT '수량',
  `success_count` int NOT NULL DEFAULT '0' COMMENT '발급수량',
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성시각',
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정시각',
  PRIMARY KEY (`coupon_event_item_id`),
  UNIQUE KEY `uk_coupon_event_item_event_type` (`coupon_event_id`,`coupon_type_id`),
  KEY `idx_coupon_event_item_type` (`coupon_type_id`),
  CONSTRAINT `chk_coupon_event_item_quantity` CHECK ((`quantity` > 0)),
  CONSTRAINT `chk_coupon_event_item_success_count` CHECK (((`success_count` >= 0) and (`success_count` <= `quantity`)))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `coupon_claim_request` (
  `coupon_claim_request_id` bigint NOT NULL AUTO_INCREMENT COMMENT '식별자',
  `coupon_event_id` bigint NOT NULL COMMENT '쿠폰이벤트식별자',
  `coupon_event_occurrence_id` bigint DEFAULT NULL COMMENT '쿠폰이벤트회차식별자',
  `coupon_event_item_id` bigint NOT NULL COMMENT '쿠폰식별자',
  `user_id` bigint NOT NULL COMMENT '유저식별자',
  `request_status` varchar(30) NOT NULL DEFAULT 'PENDING' COMMENT '쿠폰발급상태',
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성시각',
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정시각',
  `completed_at` datetime(6) DEFAULT NULL COMMENT '처리 완료 시각',
  `failure_code` varchar(30) DEFAULT NULL COMMENT '실패코드',
  `failure_reason` varchar(500) DEFAULT NULL COMMENT '실패사유',
  PRIMARY KEY (`coupon_claim_request_id`),
  UNIQUE KEY `uk_claim_request_user_occurrence` (`user_id`,`coupon_event_occurrence_id`),
  KEY `idx_claim_request_event_status` (`coupon_event_id`,`request_status`),
  KEY `idx_claim_request_item` (`coupon_event_item_id`),
  KEY `idx_claim_request_occurrence` (`coupon_event_occurrence_id`),
  CONSTRAINT `fk_claim_request_occurrence` FOREIGN KEY (`coupon_event_occurrence_id`) REFERENCES `coupon_event_occurrence` (`coupon_event_occurrence_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `chk_claim_request_status` CHECK ((`request_status` in (_utf8mb4'PENDING',_utf8mb4'SUCCESS',_utf8mb4'FAILED',_utf8mb4'CANCELLED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `user_coupon` (
  `user_coupon_id` bigint NOT NULL AUTO_INCREMENT COMMENT '식별자',
  `user_id` bigint NOT NULL COMMENT '유저식별자',
  `coupon_event_id` bigint NOT NULL COMMENT '쿠폰이벤트식별자',
  `coupon_event_occurrence_id` bigint DEFAULT NULL COMMENT '쿠폰이벤트회차식별자',
  `coupon_event_item_id` bigint NOT NULL COMMENT '쿠폰식별자',
  `coupon_code` varchar(100) NOT NULL COMMENT '쿠폰코드',
  `coupon_status` varchar(30) NOT NULL DEFAULT 'ISSUED' COMMENT '쿠폰상태',
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성시각',
  `updated_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT '수정시각',
  `claim_id` bigint NOT NULL COMMENT '발급요청식별자',
  `discount_type` varchar(20) NOT NULL COMMENT '할인타입(RATE 또는 AMOUNT)',
  `discount_value` decimal(10,2) NOT NULL COMMENT '할인값(발급시점스냅샷)',
  `expires_at` datetime(6) NOT NULL COMMENT '만료시각',
  `used_at` datetime(6) DEFAULT NULL COMMENT '사용시각',
  `cancelled_at` datetime(6) DEFAULT NULL COMMENT '취소시각',
  `cancel_reason` varchar(255) DEFAULT NULL COMMENT '취소사유',
  PRIMARY KEY (`user_coupon_id`),
  UNIQUE KEY `uk_user_coupon_code` (`coupon_code`),
  UNIQUE KEY `uk_user_coupon_claim_id` (`claim_id`),
  UNIQUE KEY `uk_user_coupon_user_occurrence` (`user_id`,`coupon_event_occurrence_id`),
  KEY `idx_user_coupon_user_status` (`user_id`,`coupon_status`),
  KEY `idx_user_coupon_event` (`coupon_event_id`),
  KEY `idx_user_coupon_user_status_expires` (`user_id`,`coupon_status`,`expires_at`,`user_coupon_id`),
  KEY `idx_user_coupon_occurrence` (`coupon_event_occurrence_id`),
  CONSTRAINT `fk_user_coupon_occurrence` FOREIGN KEY (`coupon_event_occurrence_id`) REFERENCES `coupon_event_occurrence` (`coupon_event_occurrence_id`) ON DELETE RESTRICT ON UPDATE RESTRICT,
  CONSTRAINT `chk_user_coupon_discount_type` CHECK ((`discount_type` in (_utf8mb4'RATE',_utf8mb4'AMOUNT'))),
  CONSTRAINT `chk_user_coupon_status` CHECK ((`coupon_status` in (_utf8mb4'ISSUED',_utf8mb4'USED',_utf8mb4'EXPIRED',_utf8mb4'CANCELLED')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `wallet_outbox` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '식별자',
  `aggregate_id` bigint NOT NULL COMMENT '집계식별자(userCouponId 또는 claimId)',
  `topic` varchar(100) NOT NULL COMMENT '발행토픽명',
  `payload` json NOT NULL COMMENT '이벤트페이로드',
  `status` varchar(20) NOT NULL DEFAULT 'PENDING' COMMENT '발행상태(PENDING, SENT)',
  `retry_count` int NOT NULL DEFAULT '0' COMMENT '재시도횟수',
  `created_at` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT '생성시각',
  `sent_at` datetime(6) DEFAULT NULL COMMENT '발행시각',
  PRIMARY KEY (`id`),
  KEY `idx_wallet_outbox_status_id` (`status`,`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
